name: CI

on:
  push:
  pull_request:
    branches: [main]

jobs:
  main:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node:
          - 16
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          node-version: ${{ matrix.node }}
      - run: pnpm lint:fix
