name: Test Action
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
    test:
        name: "Tests"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
      
            - name: Run the action
              uses: ./
      
            - name: 'Test: .npmrc'
              run: pnpm config get registry